name: TP
main: TPPlugin
version: 1.0
api-version: 1.16
author: lain
commands:
    tpa:
        description: 传送你到某人所在
        usage: /tpa [player]
    tpahere:
        description: 传送某人到你所在
        usage: /tpahere [player]
    tpaccept:
        description: 接受一个传送请求
        usage: /tpaccept
    tpaignore:
        description: 拒绝一个传送请求
        usage: /tpaignore